### ISSUE TITLE
This repository should be removed

### ISSUE THREAD

**Issue by ErhoSen** [roginvs/wolt-assignment#1]
Тебя ведь попросили не выкладывать решение на github; зачем же ты это сделал?

**Comment by roginvs** [comment]
@ErhoSen Кто просил, когда? Проверил переписку, не нашел нигде упоминания об этом.

В чём проблема если это кто-то увидит? Тестовое задание предполагается делать самому, и любая попытка схитрить обернётся во время испытательного срока

**Comment by ErhoSen** [comment]
Если тебя действительно не просили - вопрос снят 🤷🏻 

Теперь так:
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/5013076/190673369-98605e1f-b6dd-4d98-9166-a4b05c5d8a22.png">

**Comment by roginvs** [comment]
Наше (https://github.com/Seaber-io) тестовое чем-то похоже на это тестовое, тоже нужно данные трансформировать и потом в ui показать. Если кандидат подсмотрит этот репозиторий и сделает похоже, т.е. отделит логику трансформаций от презентации, покроет тестами транформацию, итд, то я только буду рад потому что ну хоть так научился, теперь умеет. Но, к сожалению, мало кто делает так, с учётом того что в самом тестовом у нас прописано что мы ценим и какие критерии для оценки используем

**Comment by ErhoSen** [comment]
Круто что нанимая вы даёте тестовое. 
На мой взгляд само задание и разговор "по мотивам" раскрывают кандидата намного лучше, чем любое риалтайм программирование (4 часовые секции в яндексе, ха-ха). 

Самое главное, чтобы разговор по мотивам состоялся при любом исходе, даже если тестовое не проходит формальные критерии оценивания.

То есть это некоторый контракт: я готов потратить 5-10-15 часов на тестовое, но в ответ хочу получить час интенсивного код-дизайн-ревью
